name: DS-python
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- ipython
- jupyter
- jupyterlab>=3
- numpy
- pandas>=1
- matplotlib>3
- mplleaflet
- ipympl
- seaborn
- plotnine
- pyproj
- requests
- openpyxl
