name: course-python
channels:
- conda-forge
dependencies:
- python=3.11
- ipython
- jupyter
- jupyterlab>=3
- numpy
- pandas=2.2
- matplotlib>3
- mplleaflet
- ipympl
- seaborn
- plotnine
- pyproj
- requests
- openpyxl
- geopandas
