title = "Data manipulation, analysis and visualisation in Python"
organisation = "Specialist course Doctoral schools of Ghent University"
dates = "June 8, 9 and 10, 2022"
repository = "DS-python-data-analysis"
conda_environment = "DS-python"
hackmd = "https://hackmd.io/ye6LZ9hAR-22PGiNT2OCMQ?both"
googleform = "https://forms.gle/R47g9xaJ4hRGtajN9"