title = "Data manipulation, analysis and visualisation in Python"
organisation = "Specialist course Doctoral schools of Ghent University"
dates = "27, 30 January and 3 February 2025"
repository = "DS-python-data-analysis"
conda_environment = "DS-python"
hackmd = "https://hackmd.io/J3eLIyKRQ_Kc3PRV4DLCwQ?both"
googleform = "https://forms.gle/wmFH89ELcRKFYuWFA"